### ISSUE TITLE
identify tool bug when a group is selected and results should appear in a popup on the map

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#373]
in a context with identify tool configured with `"showInMapPopup": true`, if no layers are selected, then clicking on the map queries all layers and shows a popup with arrows/pages to show results for each layers - that's fine. If a single leaf layer is selected, clicking on an object on the map queries that layer - this is fine too.

But if a group is selected, then clicking at any place on the map (even if there are no objects below) will display the last popup displayed by the previous successful layer query. If the context was just loaded and no previous successful query was done, a popup will open with the throbber spinning indefinitely.

**Comment by tdipisa** [comment]
@landryb I think it has been fixed already in one of recent versions. I'm not able to find the MS related issue but it seems working properly in MS DEV. Can you please try again and let me know? Thank you.

**Comment by landryb** [comment]
i've retested, and it's still present on 2022.01.xx.
![Peek 13-10-2022 17-04](https://user-images.githubusercontent.com/3421760/195634307-2c37cf88-f53f-4de3-818f-018f10ddf1d2.gif)

**Comment by tdipisa** [comment]
@landryb I was referring to latest MapStore master. Are you able to reproduce [here](https://georchestra.geo-solutions.it/mapstore/#/context/issue_373)?

**Comment by landryb** [comment]
> @landryb I was referring to latest MapStore master. Are you able to reproduce [here](https://georchestra.geo-solutions.it/mapstore/#/context/issue_373)?

the behaviour seems correct on this context, do you have any idea which commit/pr might have fixed it ?
