### ISSUE TITLE
[Catalog - version 2021.02.xx-] unable to download catalog data

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#468]
**Issue:**  Unable to download  layers from CSW catalogs since 2021.02.xx version deployment. 

**Version** [Image docker tagged 21.02.xx ](https://hub.docker.com/r/geosolutionsit/mapstore2-georchestra/tags) from Mapstore2geOrchestra

**Test on**  https://portail-test.sig.rennesmetropole.fr/mapstore
![image](https://user-images.githubusercontent.com/4659829/151396953-95746826-48bc-4127-9948-3f28baa15bc5.png)

Console message : 404 on https://portail-test.sig.rennesmetropole.fr/mapstore/undefined?service=WMS&version=&request=GetCapabilities

**Informations**  I didn't change the catalogs configuration from previous version (1.2.xx) nether proxy.properties. 
Does this configuration file need a modification ? I dont see that in the [documentation](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20210104-to-20210200)

**Comment by pierrejego** [comment]
We have the same problem with a non docker installation,. Mapstore version master

**Comment by tdipisa** [comment]
@catmorales it seems an undesired regression indeed. I've opened an issue in MS ([#7800](https://github.com/geosolutions-it/MapStore2/issues/7800)) to fix it shortly.

**Comment by catmorales** [comment]
@tdipisa could you please see that issue ?
We are waiting for this to deploy 21.02.xx en production.

**Comment by catmorales** [comment]
OK Thank you.

**Comment by landryb** [comment]
Fwiw, testing master (which includes the fix for geosolutions-it/MapStore2#7800) i still see this issue.

first, a CSW request is done, which only returns a single entry (while my testing catalog has 5 ?) and then a request is done on `/mapstore/undefined?service=WMS&version=&request=GetCapabilities` which fails/gets a 404.

the CSW result points at an external geoserver for this single test layer:
```
      <dc:URI protocol="WWW:DOWNLOAD-1.0-http--download" name="CRAIG_MOS_GRAND_CLERMONT_2020.zip">https://ids.craig.fr/geocat/srv/api/records/e7dae1e7-aadb-4f8a-bc9d-98464469cdcd/attachments/CRAIG_MOS_GRAND_CLERMONT_2020.zip</dc:URI>
      <dc:URI protocol="OGC:WMS" name="CRAIG_MOS_GRAND_CLERMONT_2020" description="Mode d'occupation des sols - Grand Clermont - 2020 (OGC:WMS)">https://ids.craig.fr/wxs/public/wms?</dc:URI>
      <dc:URI protocol="OGC:WFS" name="CRAIG_MOS_GRAND_CLERMONT_2020" description="Mode d'occupation des sols - Grand Clermont - 2020 (OGC:WFS)">https://ids.craig.fr/wxs/public/wms?</dc:URI>
```

**Comment by landryb** [comment]
i figured that the CSW request only returns an entry because `dc:type` is filtered on `dataset` while i have other 4 other entries in the catalog with `series`.

**Comment by tdipisa** [comment]
@landryb 

The original issue referred to the fact that adding layers from a CSW was no longer possible (at least in some cases). This has been fixed (there was a small regression), I can now do it using our DEV.

![image](https://user-images.githubusercontent.com/1280027/152972518-5b60de84-e97a-45b7-a16c-5b1b51a6ab2e.png)

> first, a CSW request is done, which only returns a single entry (while my testing catalog has 5 ?) and then a request is done on /mapstore/undefined?service=WMS&version=&request=GetCapabilities which fails/gets a 404.

This is probably a typo that is not blocking/compromising anyway the general functionality.

> i figured that the CSW request only returns an entry because dc:type is filtered on dataset while i have other 4 other entries in the catalog with series.

Also due to #257 (that probably can be closed now @MaelREBOUX) we included in MS (some time ago) the possibility to tune this aspect (defining both static and dynamic filters) in the advanced option of the catalog tool for CSW source type. The user guide for this is available [here](https://mapstore.readthedocs.io/en/latest/user-guide/catalog/#static-filter-and-dynamic-filter).

**Comment by landryb** [comment]
> > first, a CSW request is done, which only returns a single entry (while my testing catalog has 5 ?) and then a request is done on /mapstore/undefined?service=WMS&version=&request=GetCapabilities which fails/gets a 404.
> 
> This is probably a typo that is not blocking/compromising anyway the general functionality.

I dunno, but the analysis of the bug shown that this request done on `undefined` was a red herring, just reporting that it still happens; Sure, the bug itself is fixed as in layers can be added from CSW, but there's still this strange `undefined.*GetCapabilities` request done.

In the meantime i've figured out how to tweak the static filter so that both `datasets` and `series` were fetched from CSW - thanks !

**Comment by tdipisa** [comment]
> I dunno, but the analysis of the bug shown that this request done on undefined was a red herring, just reporting that it still happens; Sure, the bug itself is fixed as in layers can be added from CSW, but there's still this strange undefined.*GetCapabilities request done.

Of course @landryb and thank you so much for reporting this. I've already reported it to our developers indeed.

**Comment by tdipisa** [comment]
@alexander-fedorenko as soon as possible please provide a backport PR for mapstore2-georchestra 2021.02.xx branch to align the MS revision to the latest MS 2021.02.xx. Thank you.

**Comment by tdipisa** [comment]
> @alexander-fedorenko as soon as possible please provide a backport PR for mapstore2-georchestra 2021.02.xx branch to align the MS revision to the latest MS 2021.02.xx. Thank you.

I'm sorry @alexander-fedorenko I've just realized that you already did it with #481. Thank you.

**Comment by landryb** [comment]
for the record the strange `undefined` WMS getcapabilities requests issue is tracked in geosolutions-it/MapStore2#7849
