### ISSUE TITLE
[MS3] Update mapstore2georchestra to master  fail

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#541]
Last Thusrday, i've deployed the [latest docker image](https://hub.docker.com/layers/mapstore2-georchestra/geosolutionsit/mapstore2-georchestra/latest/images/sha256-c227b21762291514d017de602bf62ab9e5145798516a3510a4b43087bc368547?context=explore) as usual for the first time after your delivery of group 3.
On https://portail-test.sig.rennesmetropole.fr/mapstore/  I see a **503 error** and mapstore doesn't run at all. 
**503 Service Unavailable
No server is available to handle this request.**

Then, I redeployed the 2021.02.xx to make mapstore running because we need it in portail-test  ant it works.
If the problem was related to the deployment process, the 2021.02.xx version could not have been deployed and running.

My question is what is different between both versions ?

**Comment by catmorales** [comment]
MS3 pour marché subséquent 3 ;)

**Comment by pmauduit** [comment]
> MS3 pour "Marché subséquent 3" ;)

pardon ;-)

**Comment by pmauduit** [comment]
> My question is what is different between both versions ?

I don't know for the differences between both, but I can explain why the mapstore webapp in the new version does not come to life in your (rennes-métropole intranet test) environment.

It seems that all the users from the LDAP are fetched at webapp's bootstrap, then translated into Java objects. The issue is, that each user integrates a list of groups, which themselves contain a list of the user belonging to the groups. Since each geOrchestra users are member of the USER group, we have on each ones a group description with 9k users, and each user objects of the list is taking more than 700kB of heap.

See screenshot below:

![screenshot-1](https://user-images.githubusercontent.com/594335/172794186-abe6d72e-3b36-4ac5-a29c-2c0e684a2fe2.png)


Since the XMX is set to 1GB, you reach the limit when parsing the 1400-nth user.

**Comment by catmorales** [comment]
@tdipisa , so in this state we can't test group 3.
Perhaps, the adaptation to geOrchestra has not been finalised. This connexion to ldap is strange .

I will let portail-test in this state for this morning, if you want to test it.
At 4 p.m , i will revert to the 2021.02.xx version because our test platform need to be used to test another things

**Comment by tdipisa** [comment]
@catmorales I'm sorry for the late reply. We didn't experience this issue in our DEV during our tests of the update and we didn't modify the way MS connect to LDAP from the last version of course :)
We will anyway check to try to identify the reason of these failures and find a solution. I will have a call with the team tomorrow morning for a review. I will get back to you as soon as possible.

**Comment by tdipisa** [comment]
@catmorales Can you please share with us the full log file generated at startup when you run the new docker image? We need it, please. 

@jusabatier I know you have opened this #540. It seems to me you are not experiencing the same issue here, correct?

**Comment by jusabatier** [comment]
When I tested it, I didn't get any errors at mapstore's startup.

But here we have only about 1k users and an XmX options set to 2G, so it can explain why we don't have the problem explained by @pmauduit

**Comment by catmorales** [comment]
> the full log file generated at startup when you run the new docker image

In attachments
[log_error_mapstore.log](https://github.com/georchestra/mapstore2-georchestra/files/8877735/log_error_mapstore.log)

**Comment by tdipisa** [comment]
@catmorales we pushed a change. Can you please check with the [latest image](https://hub.docker.com/layers/mapstore2-georchestra/geosolutionsit/mapstore2-georchestra/latest/images/sha256-17f493606a7be08c67246a27745bda7dfd4e6be9bfe0b978d0662a557c5de943?context=explore) and let us know? Thank you.

**Comment by catmorales** [comment]
@tdipisa , ok thank you very much. I need to check with users when i can do it. 
I let you know asap.

**Comment by catmorales** [comment]
@tdipisa I cheked with the latest image and i still have issues with this docker image, i revert to the 2021.02.xx version.

However, in the mapstore logs, the message about log4j has disappeared. 
The new logs are in attachments.

[20220615_logs_mapstore2georchestra.txt](https://github.com/georchestra/mapstore2-georchestra/files/8910768/20220615_logs_mapstore2georchestra.txt)

I suggest to schedule a visio beetween your staff and @pmauduit next week.

**Comment by catmorales** [comment]
>But here we have only about 1k users and an XmX options set to 2G
 
@tdipisa what are the recommended XmX requirements for mapstore2georchestra ?

**Comment by landryb** [comment]
whatever the base requirements, the memory consumption issue growing exponentially with a large directory raised by @pmauduit has to be properly fixed in the mapstore java backend, it's totally unacceptable.

**Comment by tdipisa** [comment]
@catmorales we will then investigate this further. With this new version there has been a jump of two major version in the backend so we are checking to see if something happened in the middle that could be the cause of [this](https://github.com/georchestra/mapstore2-georchestra/issues/541#issuecomment-1150791247). You can confirm the following and thus that MapStore gets stuck on startup returning a 503 error?

> It seems that all the users from the LDAP are fetched at webapp's bootstrap

Can you also increase the log level to DEBUG and share with us the new one.

**Comment by tdipisa** [comment]
@catmorales do you have any news for the above?

**Comment by catmorales** [comment]
@tdipisa our test platform is also a pre-production platform, so i can't let it broken all time. So I have to schedule a new test. I'll try to do it this week.

**Comment by catmorales** [comment]
>@pmauduit is not free now

We have tested with @fvanderbiest. 

>It would be useful to also have all the other log files you can find in the /logs sub-directory of the Tomcat installation dir where MS is running so that we will able to double check and confirm the reason why MS is loading all the users at startup.

I send you by email the tomcat logs.

>we are checking to see if something happened in the middle that could be the cause of https://github.com/georchestra/mapstore2-georchestra/issues/541#issuecomment-1150791247

We have increased the XMx to 4G and it's not enough . 
To remind you we have 5425 users and all with the geOrchestra User rôle.
So we can't use this mapstore2 version, it's not acceptable for us.

**Comment by tdipisa** [comment]
@catmorales thank you for the information

>@tdipisa, Just now we have deployed the latest image. Could you please take a look at https://portail-test.sig.rennesmetropole.fr/ to see the 503 error ?

I saw it, thank you.

![image](https://user-images.githubusercontent.com/1280027/175340738-ecef74bd-efc0-4f79-b1eb-fb4cf80c18ee.png)

> I send you by email the tomcat logs.

Thank you so much, I'm looking forward to receiving them soon.

>We have increased the XMx to 4G and it's not enough .
To remind you we have 5425 users and all with the geOrchestra User rôle.

Ok.

>So we can't use this mapstore2 version, it's not acceptable for us.

Of course, don't worry guys, we will sort this asap.

**Comment by landryb** [comment]
should be fairly simple to reproduce creating 5k users/orgs in the ldap with a script, no ? :)

**Comment by catmorales** [comment]
I agree with Landry, this would be easier for me because i have to deploy and rollback each time to not let users in difficulties.
Every 2 minutes the container is created newly because of the insufficient memory.

**Comment by tdipisa** [comment]
> should be fairly simple to reproduce creating 5k users/orgs in the ldap with a script, no ? :)

It's usually easier and fast to provide log files to be honest :) Anyway, if it's too hard to provide them we'll find another way, no problem.

**Comment by tdipisa** [comment]
@catmorales 

We have merged today an update that should fix the problem you have  experienced. The [latest image](https://hub.docker.com/layers/mapstore2-georchestra/geosolutionsit/mapstore2-georchestra/latest/images/sha256-ad86ed42c9e96b94d01270d682e30dff4d158533e95b0b678315e6d6595c3f6a?context=explore) is available for a test.

**Comment by catmorales** [comment]
@tdipisa 
Yesterday, I have deployed the latest docker image and it has worked on a second try.
I configured the localConfig.json and pluginsConfig.json using the documentation [here](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#replacing-burgermenu-with-sidebarmenu) as explained by you and I have some questions and comentaries:
1 - the chapter called 'Updating contexts to Sidebar Menu' refers to mapstore plugins configuration into context manager  and not to all the contexts; I think  you should have to  modify it or something is wrong for me,
2 - so where or how  can I change Burger Menu to Sidebar Menu in the Context manager interface (phase 2 when creating a new context or modify an existing context)?It has not been modified by the previous configuration.
3 - how to modify all the previous application contexts ? it is not explained in the documentation and it is very important. I remember  @j explained  (but I don't remember where) how to do it in database but it should be explained in your documentation,
4 - our personal plugins (especially urbamap) don't work anymore, we saw in the documentation [here](https://mapstore.readthedocs.io/en/latest/developer-guide/extensions/#managing-drawing-interactions-conflict-in-extension) that we will have to adapt them at the new version. 

So at the moment, I had to revert to the 2021.02.xx version on portail-test waiting the end of urbamap development on this version (next week I hope) and then I will re-deploy the latest docker image (version 22.xx) to test your last developments and corrections.
Thank you to have a look at the @Gaetanbrl issues relatives to this problems

**Comment by Gaetanbrl** [comment]
> our personal plugins (especially urbamap) don't work anymore

Same for Cadastrapp no ?

**Comment by catmorales** [comment]
bq.Same for Cadastrapp no ?

Yes but i didn't deployed the [last version](https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/v2.0.0-rc) of the cadastrapp plugin , I hope, it will resolve cadastrapp problems.

**Comment by jusabatier** [comment]
There was an update for cadastrapp & urbanisme to handle the sidebar integration.

For what I tested, it looks to work well with it.

**Comment by tdipisa** [comment]
Hi @catmorales 

>1 - the chapter called 'Updating contexts to Sidebar Menu' refers to mapstore plugins configuration into context manager and not to all the contexts; I think you should have to modify it or something is wrong for me,

Yes, it is referring to the default configuration for new created app contexts. We have improved the documentation to better clarify that point. Thank you.

>2 - so where or how can I change Burger Menu to Sidebar Menu in the Context manager interface (phase 2 when creating a new context or modify an existing context)?It has not been modified by the previous configuration.
>3 - how to modify all the previous application contexts ? it is not explained in the documentation and it is very important. I remember @jusabatier explained (but I don't remember where) how to do it in database but it should be explained in your documentation,

As per point 1 above the update of the pluginsConfig.json file allows the context editor to manually remove the Burger Menu  tool from the list of plugins of existing app contexts. Doing that the new Sidebar component will be automatically used. Basically now, when you configure a context, you have the possibility to choose the component you prefer: the Sidebar is the default but the Burger Menu is used instead if you add it to the plugin list on the right. 

For what concern the update of the other existing app contexts that have been created with previous versions of MS you have two choices:
- Update each context manually one by one to use the Sidebar by using the wizard and removing the Burger Menu item from the list on the right
- Run an SQL script on the MS DB (the one provided by @jusabatier we have also verified) to do it in batch for all existing contexts (if you want/need) 

**_We have decided to give to the maintainers the final choice while updating MS to the new version to make them able to properly manage the existing contexts according to their needs (eg. considering also the possible presence of custom extensions that need to be updated to be used with the new Sidebar component)._**

>4 - our personal plugins (especially urbamap) don't work anymore, we saw in the documentation [here](https://mapstore.readthedocs.io/en/latest/developer-guide/extensions/#managing-drawing-interactions-conflict-in-extension) that we will have to adapt them at the new version.

Existing custom extensions need to be updated a bit to be used within the new Sidebar component. We have indeed included in our DEV guide all the needed guidelines to document what need to be done for this and why. The relevant sections of the documentation are the following ones:

- [Managing drawing interactions conflict in extension](https://mapstore.readthedocs.io/en/latest/developer-guide/extensions/#managing-drawing-interactions-conflict-in-extension)
- [Using "ResponsiveContainer" for dock panels](https://mapstore.readthedocs.io/en/latest/developer-guide/extensions/#using-responsivecontainer-for-dock-panels)
- [Making other dock panels closed automatically when extension panel is open](https://mapstore.readthedocs.io/en/latest/developer-guide/extensions/#making-other-dock-panels-closed-automatically-when-extension-panel-is-open)

We have already updated both [_Cadastrapp_ ](https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/v2.0.0-rc) and [_Urbanisme_](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/v2.0.0-rc) extensions accordingly and also the _Longitudinal Profile_ extension has been developed to be compatible from the beginning.

>Thank you to have a look at the @Gaetanbrl issues relatives to this problems

Which issues you are referring too? You mean https://github.com/geosolutions-it/MapStoreExtension/issues/17 ?

**Comment by Gaetanbrl** [comment]
> Which issues you are referring too? You mean https://github.com/geosolutions-it/MapStoreExtension/issues/17 ?

@tdipisa this issue https://github.com/geosolutions-it/MapStoreExtension/issues/30

**Comment by jusabatier** [comment]
Here is the script for info : https://github.com/georchestra/mapstore2-georchestra/issues/540#issuecomment-1152225187

**Comment by catmorales** [comment]
>We have improved the documentation to better clarify that point. Thank you.

Thank you , I saw it. It's much better

**Comment by landryb** [comment]
> @catmorales
> 
> We have merged today an update that should fix the problem you have experienced. The [latest image](https://hub.docker.com/layers/mapstore2-georchestra/geosolutionsit/mapstore2-georchestra/latest/images/sha256-ad86ed42c9e96b94d01270d682e30dff4d158533e95b0b678315e6d6595c3f6a?context=explore) is available for a test.

Fwiw, (and we really shouldn't have to dig other's projects issue trackers to find it out, as already mentioned several times to @tdipisa) the corresponding fixes for the 'ldap directory is too large and consumes too much memory' issue (which was analyzed by @pmauduit) are in PR geosolutions-it/geostore#292 which fixes geosolutions-it/geostore#290

and finally, this PR landed (to my understanding) in ms2-georchestra project via PR #546

**Comment by catmorales** [comment]
@tdipisa i have the same problem described in https://github.com/georchestra/mapstore2-georchestra/issues/541#issue-1264968078 deploying https://hub.docker.com/layers/geosolutionsit/mapstore2-georchestra/2022.02.00-RC2-geOrchestra/images/sha256-d3a0244b8a7088f3c284a19e8e1cd188990ad7986fe7d4b3c0d9ec1aff6ed23f?context=explore today.
Did you apply the fix in this release ?

**Comment by tdipisa** [comment]
@catmorales mh... the backend version we released with [2022.02.00-RC2-geOrchestra](https://github.com/georchestra/mapstore2-georchestra/releases/tag/2022.02.00-RC2-geOrchestra) ([geostore v1.9.0](https://github.com/geosolutions-it/geostore/releases/tag/v1.9.0)) is exactly the same we released with [2022.02.00-RC1-geOrchestra](https://github.com/georchestra/mapstore2-georchestra/releases/tag/2022.02.00-RC1-geOrchestra). It contains the [LDAP fix](https://github.com/geosolutions-it/geostore/pull/292). 

It seemed to me you had no problems with 2022.02.00-RC1-geOrchestra. Isn't it?

**Comment by tdipisa** [comment]
@catmorales wait, its seems we simply forgot yo update the backend version in the downstream project. I will get back to you asap.

**Comment by tdipisa** [comment]
@catmorales 

> @catmorales wait, maybe we simply forgot to update the backend version in the downstream project. I will get back to you asap with a confirmation.

not properly. We forgot to do it (I've just raised a [PR for this](https://github.com/georchestra/mapstore2-georchestra/pull/561)), waiting for the review from @offtherailz, but all branches/tags (master, 2022.02.xx,  2022.02.00-RC1-geOrchestra, 2022.02.00-RC2-geOrchestra) are using geostore 1.8.x where the [LDAP fix](https://github.com/geosolutions-it/geostore/pull/292) is anyway present (since we have effectively released it in July, indeed) so it should work well.

I'm looking forward to hearing from you about this:

>It seemed to me you had no problems with 2022.02.00-RC1-geOrchestra. Isn't it? Please, let me know.

**Comment by catmorales** [comment]
We found with @pmauduit ) the reason of this 503.
It was because the health check of rancher was fixed at 60s and mapstore need more than 3 minutes to be deployed.
So we changed it and now we can deploy all tags..
Bur perhaps you're PR could solve Julien'issues https://github.com/georchestra/mapstore2-georchestra/issues/562
